import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import { PrismaClient } from '@prisma/client'
import Link from 'next/link'

const prisma = new PrismaClient()

export default function Home({ data }) {

      /* This variable for input data */
      const [formData, setFormData] = useState({})
      const [movies, setMovies] = useState(data)

      /* This arrow function to define saveMovie */
          // const saveMovie = e => {
          //   e.preventDefault();
          //   console.log(formData);
          // }
      
      /* This async function to define saveMovie */
      async function saveMovie(e) {
          e.preventDefault();
          setMovies([...movies, formData])
          /* set movies distructuring */
          const response = await fetch('/api/movies', {
              method: 'POST',
              body: JSON.stringify(formData)
          })

          return await response.json()
      }
      
      


  /* This for read data */
  return (
    <div className={styles.container}>
      <Head>
        <title>Movie List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

          <ul className={styles.movielist}>
              {movies.map(item => (
                <li key="item.id">
                <span><strong>{item.title}</strong></span>
                <span>{item.year}</span>
                <span>{item.description}</span>
                <Link href={`/movies/${item.slug}`}>
                    <a>More About this movie</a>
                </Link>
                </li>
              ))}
          </ul>

          {/* This form to input data */}
          <form className={styles.movieform} onSubmit={saveMovie}>
            <input type="text" placeholder="Enter the title movie.." name="title" onChange={e=> setFormData({ ...formData, title: e.target.value })} />
            <input type="text" placeholder="Enter the year movie.." name="year" onChange={e=> setFormData({ ...formData, year: +e.target.value })} />
            <textarea name="description" id="" cols="30" rows="10" placeholder="Enter the description movie.." onChange={e=> setFormData({ ...formData, description: e.target.value })} />
            <input type="text" placeholder="Enter the slug.." name="slug" onChange={e=> setFormData({ ...formData, slug: e.target.value })} />
            <button type="submit">Add New Movie</button>
          </form> 
                
      </main>
    </div>
  )
}

export async function getServerSideProps() {

  const movies = await prisma.movie.findMany()

  // const data = [
  //   {
  //     id: 1,
  //     title: "title",
  //   },
  //   {
  //     id: 2,
  //     title: "another title",
  //   },
  // ];

  return {
    props: {
      data: movies 
    }
  }
}

